### ISSUE TITLE
Topic Mismatch Error

### ISSUE THREAD

**Issue by dbaldwin** [ARK-Electronics/px4_ros2_examples_ws#4]
@patrikpordi first off, thank you for the tutorial. It's very relevant to some of the work we're doing with the ARK Pi6X Flow board in our DEXI drone. I'm wondering if you've run into this error before:

![Screenshot from 2024-07-31 22-19-19](https://github.com/user-attachments/assets/761f3b06-4f76-4e5a-a673-843804a5fdca)

I'm running PX4 main but perhaps I should be using a stable release? I tried with 1.14 but realized that the /fmu/out/vehicle_land_detected topic wasn't configured, which appears to be a dependency for your example. Any ideas would be much appreciated.

**Comment by patrikpordi** [comment]
@dbaldwin Thank you for checking the tutorial out. I haven't seen this error before, but I will try to reproduce it.
If you use 1.14 you can refer to the pull request below.
https://github.com/PX4/PX4-Autopilot/pull/23328
In addition I am using:
```
oem@oem-Legion-5-Pro-16ITH6:~/ARK/PX4-Autopilot$ git describe --tags
v1.15.0-beta1-263-g0851517f20
```

**Comment by patrikpordi** [comment]
@dbaldwin The problem seems to be that the px4_msgs repository is not aligned with the definitions in PX4. Updating it causes a mismatch with the px4_ros2_interface_lib. I believe the simplest solution is to use an earlier version of PX4 for now. To do this, follow these steps:
```
cd PX4-Autopilot
git fetch origin
git checkout 8070c70
git submodule update --init --recursive
```

Please let me know if this resolves your issue!

**Comment by dbaldwin** [comment]
@patrikpordi I actually got it working earlier this morning based on your suggestion. This tagged version works for me:

https://github.com/PX4/PX4-Autopilot/tree/v1.15.0-beta1

Thanks for the prompt reply. I'm going to close this out!
